.TH audiorecorder 1 "github.com/amiaopensource/audiorecorder" "2018\-06\-15" "AMIA Open Source"
.SH NAME
audiorecorder \- Tool for calibration and recording of analog audio sources
.SH SYNOPSIS
\fBaudiorecorder\fR [\fB\-e\fR | \fB\-p\fR | \fB\-m\fR | \fB\-b\fR | \fB\-h\fR]
.SH OPTIONS
.TP
.B \-e
edit config
.TP
.B \-p
passthrough mode
.TP
.B \-m
edit metadata to be used in BWF creation
.TP
.B \-b
embed BEXT chunk (BWF metadata) in target file
.TP
.B \-h
display a help message
.SH LICENSE
.TP
The audiorecorder script is covered under a BSD 3\-clause license.
.TP
All documentation for audiorecorder is licensed under a Creative Commons Attribution 4.0 International License.
