#!/usr/bin/env bash
config="$HOME/.$(basename "${0}").conf"
bwf_config="$HOME/.$(basename "${0}")_BWF.conf"
touch "${config}"
touch "${bwf_config}"
. "$config"
. "${bwf_config}"

_usage(){
    echo "Usage: $(basename "${0}") [ -h | -e | -p | -m | -b ]"
    echo "  -h  display this help menu"
    echo "  -e  edit"
    echo "  -p  passthrough"
    echo "  -m  metadata"
    echo "  -b  bext"
}

OPTIND=1
while getopts ":hepmb" opt ; do
    case "${opt}" in
        h) _usage ; exit 0 ;;
        e) runtype="edit" ;;
        p) runtype="passthrough" ;;
        m) runtype="metadata" ;;
        b) runtype="bext";;
        *) echo "Error: bad option -${OPTARG}" ; _usage ; exit 1 ;;
    esac
done

_lookup_devices(){
    OLDIFS="$IFS"
    device_list=("$(ffmpeg -hide_banner -f avfoundation -list_devices true -i "" -f null /dev/null 2>&1 | cut -d ' ' -f6- | sed -e                  '1,/AVFoundation audio devices:/d' | grep -v '^$'| tr '\n' ',' )")
    IFS=',' read -r -a DEVICES <<< "$device_list"
    IFS="$OLDIFS"
}

_lookup_sample_rate(){
    case "${1}" in
        "44.1 kHz")
            SAMPLE_RATE_NUMERIC="44100"
            ;;
        "48 kHz")
            SAMPLE_RATE_NUMERIC="48000"
            ;;
        "96 kHz")
            SAMPLE_RATE_NUMERIC="96000"
            ;;
    esac
}

_lookup_bit_depth(){
    case "${1}" in
        "16 bit")
            CODEC="pcm_s16le"
            ;;
        "24 bit")
            CODEC="pcm_s24le"
            ;;
    esac
}

_get_ITEM_ID(){
    echo "Please Input Item ID or type Q to exit"
    read ITEM_ID
    if [[ "${ITEM_ID}" = [Qq] ]] ; then
        echo "Goodbye!"
        exit 0
    fi
    if [ -f "${output}/${ITEM_ID}.wav" ] ; then
        echo "A file with that name already exists!"
        _get_ITEM_ID
    fi
}

_metadata_gui(){
    gui_conf="
    # Set transparency: 0 is transparent, 1 is opaque
    *.transparency=0.95
    # Set window title
    *.title = Edit Metadata Values
    # intro text
    intro.width = 300
    intro.type = text
    intro.text = Hello
    #Originator
    originator.type = textfield
    originator.label = Enter Originator
    originator.default = "${originator}"
    #Coding History
    coding_history.type = textbox
    coding_history.label = Enter Coding History
    coding_history.default = "${coding_history}"
    cb.type = cancelbutton
    cb.label = Cancel
    "

    pashua_configfile=$(/usr/bin/mktemp /tmp/pashua_XXXXXXXXX)
    echo "${gui_conf}" > "${pashua_configfile}"
    pashua_run
    rm "${pashua_configfile}"
}

_master_gui(){
    _lookup_devices
    gui_conf="
    # Set transparency: 0 is transparent, 1 is opaque
    *.transparency=0.95
    # Set window title
    *.title = Welcome to Audio Recorder!
    # intro text
    intro.width = 300
    intro.type = text
    intro.text = Hello
    #Output Location
    output.type = openbrowser
    output.label = Output Location
    output.default = "${output}"
    #Sample Rate
    sample_rate.type = radiobutton
    sample_rate.label = Select Sample Rate
    sample_rate.option = 44.1 kHz
    sample_rate.option = 48 kHz
    sample_rate.option = 96 kHz
    sample_rate.default = "${sample_rate}"
    #Bit Depth
    bit_depth.type = radiobutton
    bit_depth.label = Select Bit Depth
    bit_depth.option = 16 bit
    bit_depth.option = 24 bit
    bit_depth.default = "${bit_depth}"
    #Enable BWF
    bwf.type = checkbox
    bwf.label = Embed BWF Metadata
    bwf.default = "${bwf}"
    #Enable Trim
    trim.type = radiobutton
    trim.label = Trim Silence
    trim.option = Off
    trim.option = Auto
    trim.default = "${trim}"
    #Cancel Button
    cb.type = cancelbutton
    cb.label = Cancel
    "

    pashua_configfile=$(/usr/bin/mktemp /tmp/pashua_XXXXXXXXX)
    echo "${gui_conf}" > "${pashua_configfile}"
    pashua_run
    rm "${pashua_configfile}"
}

_embed_bext(){
    echo "Preparing to embed metadata"
    echo ""
    if (("${#ITEM_ID}" > 32)) ; then
        orig_ref="See description for Identifiers"
    else
        orig_ref="${ITEM_ID}"
    fi

    bwfmetaedit --reject-overwrite --Description="${ITEM_ID}".wav --Originator="${originator}" --OriginatorReference="${orig_ref}" --History="${coding_history}" --IARL="${originator}" --MD5-Embed --OriginationDate=$(date "+%Y-%m-%d") --OriginationTime=$(date "+%H:%M:%S") "${BEXT_TARGET}"
}

pashua_run() {
    # Wrapper function for interfacing to Pashua. Written by Carsten
    # Bluem <carsten@bluem.net> in 10/2003, modified in 12/2003 (including
    # a code snippet contributed by Tor Sigurdsson), 08/2004 and 12/2004.
    # Write config file

    # Find Pashua binary. We do search both . and dirname "$0"
    # , as in a doubleclickable application, cwd is /
    # BTW, all these quotes below are necessary to handle paths
    # containing spaces.
    bundlepath="Pashua.app/Contents/MacOS/Pashua"
    mypath=$(dirname "${0}")
    for searchpath in "$mypath/Pashua" "$mypath/$bundlepath" "./$bundlepath" \
                      "/Applications/$bundlepath" "$HOME/Applications/$bundlepath"
    do
        if [ -f "$searchpath" -a -x "$searchpath" ] ; then
            pashuapath=$searchpath
            break
        fi
    done
    if [ ! "$pashuapath" ] ; then
        echo "Error: Pashua is not found."
        break 2
    fi
    encoding=""
    # Get result
    result=$("$pashuapath" $encoding $pashua_configfile | sed 's/ /;;;/g')

    # Parse result
    for line in $result ; do
        key=$(echo $line | sed 's/^\([^=]*\)=.*$/\1/')
        value=$(echo $line | sed 's/^[^=]*=\(.*\)$/\1/' | sed 's/;;;/ /g')
        varname=$key
        varvalue="$value"
        eval $varname='$varvalue'
    done
} # pashua_run()

if [ "${runtype}" = "edit" ] ; then
    _master_gui

    {
    echo "output=\"${output}\""
    echo "sample_rate=\"${sample_rate}\""
    echo "bit_depth=\"${bit_depth}\""
    echo "bwf=\"${bwf}\""
    echo "trim=\"${trim}\""
    } > "${config}"
fi
if [ "${runtype}" = "metadata" ] ; then
    _metadata_gui

    {
    echo "originator=\"${originator}\""
    echo "coding_history=\"${coding_history}\""
    } > "${bwf_config}"
fi

if [ -n "${sample_rate}" ] ; then
    _lookup_sample_rate "${sample_rate}"
else
    echo "No Sample Rate Specified.  Setting to 96kH."
    SAMPLE_RATE_NUMERIC="96000"
fi
if [ -n "${bit_depth}" ] ; then
    _lookup_bit_depth  "${bit_depth}"
else
    echo "No Bit Depth Specified.  Setting to 24."
    CODEC="pcm_s24le"
fi

if [ -z "${output}" ] ; then
    echo "No Output Location Specified.  Setting Output to Desktop"
    output="~/Desktop"
fi

FILTER_CHAIN="asplit=6[out1][a][b][c][d][e],\
[e]showvolume=w=700:c=0xff0000:r=30[e1],\
[a]showfreqs=mode=bar:cmode=separate:size=300x300:colors=magenta|yellow[a1],\
[a1]drawbox=12:0:3:300:white@0.2[a2],[a2]drawbox=66:0:3:300:white@0.2[a3],[a3]drawbox=135:0:3:300:white@0.2[a4],[a4]drawbox=202:0:3:300:white@0.2[a5],[a5]drawbox=271:0:3:300:white@0.2[aa],\
[b]avectorscope=s=300x300:r=30:zoom=5[b1],\
[b1]drawgrid=x=150:y=150:c=white@0.3[bb],\
[c]showspectrum=s=400x600:mode=combined:color=rainbow:scale=lin:saturation=4[cc],\
[d]astats=metadata=1:reset=1,adrawgraph=lavfi.astats.Overall.Peak_level:max=0:min=-30.0:size=700x256:bg=Black[dd],\
[dd]drawbox=0:0:700:42:hotpink@0.2:t=42[ddd],\
[aa][bb]vstack[aabb],[aabb][cc]hstack[aabbcc],[aabbcc][ddd]vstack[aabbccdd],[e1][aabbccdd]vstack[z],\
[z]drawtext=fontfile=/Library/Fonts/Andale Mono.ttf: text='%{pts \\: hms}':x=460: y=50:fontcolor=white:fontsize=30:box=1:boxcolor=0x00000000@1[fps],[fps]fps=fps=30[out0]"

# BEXT mode
if [ "${runtype}" = "bext" ] ; then
    ITEM_ID=$(echo $(basename "${2}") | cut -d'.' -f1)
    BEXT_TARGET="${2}"
    _embed_bext
    exit 0
fi

# Passthrough mode
if [ "${runtype}" = "passthrough" ] ; then
    rec -r "${SAMPLE_RATE_NUMERIC}" -b 32 -L -e signed-integer --buffer 131072 -p | ffmpeg -i - -f wav -c:a pcm_s16le -ar 44100 - |\
    ffplay -window_title "Audio Recorder" -f lavfi \
    "amovie='pipe\:0',${FILTER_CHAIN}"
    stty sane
    exit
fi

# Record Mode
_get_ITEM_ID

if [ -e PIPE2REC ] ; then
    rm -r PIPE2REC
fi

mkfifo PIPE2REC
ASTATS_OUT=$(mktemp /tmp/temp.XXXX)
rec -r "${SAMPLE_RATE_NUMERIC}" -b 32 -L -e signed-integer --buffer 131072 -p | ffmpeg -i - -f wav -c:a "${CODEC}" -ar "${SAMPLE_RATE_NUMERIC}" -y PIPE2REC -f wav -c:a pcm_s16le -ar 44100 - |\
ffplay -window_title "Audio Recorder" -f lavfi \
"amovie='pipe\:0',${FILTER_CHAIN}" 2>"${ASTATS_OUT}"| ffmpeg -i PIPE2REC -c:a "${CODEC}" -sample_rate "${SAMPLE_RATE_NUMERIC}" -rf64 auto "${output}"/"${ITEM_ID}".wav

# Cleanup
stty sane
rm -r PIPE2REC

# Post Recording Stats
PEAK_COUNT=$(cat "${ASTATS_OUT}" | tail -n -8 | grep "Peak count" | cut -d':' -f2 | cut -c 2- | cut -d'.' -f1)

if [ "${PEAK_COUNT}" -gt "4" ] ; then
    echo -e "\033[101mWarning: There are $((${PEAK_COUNT} - 2)) samples with peaked levels in this recording.\033[0m"
fi

ASTATS=$(cat "${ASTATS_OUT}" | tail -n -8 | cut -d']' -f2 | cut -c 2- | head -n 4)
echo -e "\033[104mLevels from recorded file are:\033[0m"
echo -e "\033[104m${ASTATS}\033[0m"
# Preview File
if [ "${trim}" = "Auto" ] ; then
    Echo "Press Return to listen to preview of auto-trimmed file"
    read null
    mpv "${output}/${ITEM_ID}.wav" --force-window  --keep-open=yes --title="Trim Preview" --geometry=600x400 --af=lavfi=[silenceremove=1:0.5:-55dB:1:0.5:-55dB]
    echo "Press Y to trim file with these settings?"
    read TRIM_RESPONSE
    if [[ "${TRIM_RESPONSE}" = [Yy] ]] ; then
        ffmpeg -i "${output}/${ITEM_ID}.wav" -c:a "${CODEC}" -sample_rate "${SAMPLE_RATE_NUMERIC}" -af silenceremove=1:0.5:-55dB:1:0.5:-55dB "${output}/${ITEM_ID}_trim.wav"
    fi
else
    Echo "Press Return to listen to recorded file"
    read null
    mpv --force-window  --keep-open=yes --title=Preview --geometry=600x400 "${output}/${ITEM_ID}.wav"
fi

# Embed metadata in BEXT
if [ "${bwf}" = "1" ] ; then
    BEXT_TARGET="${output}/${ITEM_ID}.wav"
    _embed_bext
fi

#Cascadia Now!
