.TH audiorecorder 1 "github.com/amiaopensource/audiorecorder" "2017\-06\-03" "AMIA Open Source"
.SH NAME
audiorecorder - Tool for calibration and recording of analog audio sources
.SH SYNOPSIS
.B audiorecorder [-e | -p | -m | -b | -h]
.SH OPTIONS
.TP
.B -e
edit
.TP
.B -p
passthrough
.TP
.B -m
metadata
.TP
.B -b
bext
.TP
.B -h
display a help message
.SH LICENSE
audiorecorder is licensed under a Creative Commons Attribution 4.0 International License.
